### ISSUE TITLE
模块分离导致报错

### ISSUE THREAD

**Issue by LinuxSuRen** [LinuxSuRen/phoenix.webui.framework.archetype#2]
信息: Closing org.springframework.context.support.ClassPathXmlApplicationContext@704a52ec: startup date [Sat May 27 15:42:31 CST 2017]; root of context hierarchy
Exception in thread "main" java.lang.NoClassDefFoundError: org/suren/autotest/webdriver/downloader/PathUtil
	at org.suren.autotest.web.framework.validation.Validation.validation(Validation.java:54)
	at org.suren.autotest.web.framework.validation.Validation.validationFramework(Validation.java:74)
	at org.suren.autotest.web.framework.settings.SettingUtil.readFromClassPath(SettingUtil.java:176)
	at ffddfdf.Test.main(Test.java:25)
Caused by: java.lang.ClassNotFoundException: org.suren.autotest.webdriver.downloader.PathUtil
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 4 more

Process finished with exit code 1

**Comment by LinuxSuRen** [comment]
已修正。
